name: Build and Deploy Go Backend and React Frontend

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'backend'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Test and Build Go Backend
      run: |
        cd backend
        go test ./...
        go build -o server ./cmd/server

    - name: Deploy Go Backend
      run: echo "Deploy backend to your server or platform"

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'frontend'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install and Build React Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy React Frontend
      run: echo "Deploy frontend to your static site hosting service"
