name: Go Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, windows/amd64, darwin/amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Build for ${{ matrix.platform }}
      run: GOOS=${{ matrix.platform }} go build -v ./...
