name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Build Docker image
      run: docker build . -t my-go-app:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push my-go-app:${{ github.sha }}

    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/my-go-app my-go-app=my-go-app:${{ github.sha }}
        kubectl rollout status deployment/my-go-app
