name: Go Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest
    
    - name: Run golint
      run: golint ./...
